use_frameworks!
target 'ConnectionKit_Tests' do
  platform :ios, '8.0'
  pod 'ConnectionKit', :path => '../'
  
  pod 'RepresentationKit', :git => 'https://github.com/averello/RepresentationKit.git'
  pod 'CocoaAsyncSocket', :git => 'https://github.com/averello/CocoaAsyncSocket.git'
  
end
